import pandas as pd
import matplotlib.pyplot as plt
import os

# Load benchmark and performance data
benchmark_df = pd.read_csv('benchmark_results.csv')
performance_df = pd.read_csv('model_performance_report.csv')

# Generate HTML
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Anomaly Detection - Full Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f9f9f9; color: #333; }}
    h1 {{ color: #0d47a1; }}
    h2 {{ border-bottom: 2px solid #ccc; padding-bottom: 5px; color: #1a237e; }}
    img {{ width: 80%; max-width: 800px; margin: 20px 0; box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.1); }}
    table {{ width: 80%; border-collapse: collapse; margin: 20px 0; background-color: white; }}
    th, td {{ border: 1px solid #ddd; padding: 10px; text-align: center; }}
    th {{ background-color: #e3f2fd; }}
    footer {{ margin-top: 50px; font-size: 0.9em; color: #888; }}
    .section {{ margin-bottom: 40px; }}
  </style>
</head>
<body>

  <h1>Anomaly Detection Project Report</h1>

  <div class="section">
    <h2>Model Performance Metrics</h2>
    {performance_df.to_html(index=False)}
    <img src="model_evaluation_curves.png" alt="Model Evaluation Curves">
  </div>

  <div class="section">
    <h2>Computation Benchmark Results</h2>
    {benchmark_df.to_html(index=False)}
    <img src="inference_time_comparison.png" alt="Inference Time Comparison">
    <img src="throughput_comparison.png" alt="Throughput Comparison">
    <img src="resource_usage_comparison.png" alt="Resource Usage Comparison">
  </div>

  <footer>
    Generated by Anomaly Detection Project · {pd.Timestamp.now().strftime('%B %Y')}
  </footer>

</body>
</html>
"""

with open('full_report.html', 'w') as f:
    f.write(html_content)

print("✅ Full report generated as 'full_report.html'")
