import pandas as pd
import matplotlib.pyplot as plt
import os

# Load benchmark data
df = pd.read_csv('benchmark_results.csv')

chart_dir = 'benchmark_charts'
if not os.path.exists(chart_dir):
    os.makedirs(chart_dir)

# Generate Charts Function
def generate_chart(column, ylabel, filename, color):
    plt.figure(figsize=(8,5))
    plt.bar(df['Environment'], df[column], color=color)
    plt.ylabel(ylabel)
    plt.title(f'{ylabel} Across Environments')
    plt.savefig(f'{chart_dir}/{filename}')
    plt.close()

# Generate Required Charts
generate_chart('Inference Time (s)', 'Inference Time (s)', 'inference_time_comparison.png', 'cornflowerblue')
generate_chart('Throughput (rows/sec)', 'Throughput (rows/sec)', 'throughput_comparison.png', 'mediumseagreen')
generate_chart('CPU Usage Change (%)', 'CPU Usage Change (%)', 'cpu_usage_comparison.png', 'salmon')
generate_chart('Memory Usage (MB)', 'Memory Usage (MB)', 'memory_usage_comparison.png', 'gold')

# Generate HTML
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Computation Benchmark - Anomaly Detection</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f9f9f9; color: #333; }}
    h1 {{ color: #0d47a1; }}
    h2 {{ border-bottom: 2px solid #ccc; padding-bottom: 5px; color: #1a237e; }}
    img {{ width: 80%; max-width: 800px; margin: 20px 0; box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.1); }}
    table {{ width: 80%; border-collapse: collapse; margin: 20px 0; background-color: white; }}
    th, td {{ border: 1px solid #ddd; padding: 10px; text-align: center; }}
    th {{ background-color: #e3f2fd; }}
    footer {{ margin-top: 50px; font-size: 0.9em; color: #888; }}
  </style>
</head>
<body>

  <h1>Computation Benchmark Results</h1>
  <h2>Benchmark Summary Table</h2>
  {df.to_html(index=False)}

  <h2>Inference Time Comparison</h2>
  <img src="{chart_dir}/inference_time_comparison.png">

  <h2>Throughput Comparison</h2>
  <img src="{chart_dir}/throughput_comparison.png">

  <h2>CPU Usage Change</h2>
  <img src="{chart_dir}/cpu_usage_comparison.png">

  <h2>Memory Usage</h2>
  <img src="{chart_dir}/memory_usage_comparison.png">

  <footer>
    Generated by Anomaly Detection Benchmarking Project · April 2025
  </footer>

</body>
</html>
"""

with open('benchmark.html', 'w') as f:
    f.write(html_content)

print("✅ Computation benchmark report generated as 'benchmark.html'")
